"""empty message

Revision ID: 166b1abacfd0
Revises: f53886c3a590
Create Date: 2025-02-26 17:17:21.421058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166b1abacfd0'
down_revision: Union[str, None] = 'f53886c3a590'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.drop_column('admin', 'number_of_tries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('number_of_tries', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('config')
    # ### end Alembic commands ###
