"""empty message

Revision ID: 267fd06da6e1
Revises: 5fae4b8ffa9b
Create Date: 2025-02-26 21:24:50.817308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '267fd06da6e1'
down_revision: Union[str, None] = '5fae4b8ffa9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('subscribed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('list', 'subscribed')
    # ### end Alembic commands ###
