"""empty message

Revision ID: 2994a4a8fe84
Revises: 481c683c53ec
Create Date: 2025-02-26 21:14:20.787461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2994a4a8fe84'
down_revision: Union[str, None] = '481c683c53ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('referral_code', sa.String(), nullable=False))
    op.add_column('list', sa.Column('state', sa.String(), nullable=True))
    op.alter_column('list', 'zip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('list_referral_number_key', 'list', type_='unique')
    op.create_unique_constraint(None, 'list', ['referral_code'])
    op.drop_column('list', 'referral_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('referral_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'list', type_='unique')
    op.create_unique_constraint('list_referral_number_key', 'list', ['referral_number'])
    op.alter_column('list', 'zip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('list', 'state')
    op.drop_column('list', 'referral_code')
    # ### end Alembic commands ###
