"""empty message

Revision ID: 5fae4b8ffa9b
Revises: 52a87bd3c0c2
Create Date: 2025-02-26 21:21:45.438822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fae4b8ffa9b'
down_revision: Union[str, None] = '52a87bd3c0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('country_code', sa.String(length=2), nullable=False))
    op.add_column('list', sa.Column('state_code', sa.String(length=2), nullable=True))
    op.drop_column('list', 'country')
    op.drop_column('list', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('list', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('list', 'state_code')
    op.drop_column('list', 'country_code')
    # ### end Alembic commands ###
