"""empty message

Revision ID: 8a71fde28db1
Revises: 1f3fe30b6153
Create Date: 2025-02-26 22:46:23.825983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a71fde28db1'
down_revision: Union[str, None] = '1f3fe30b6153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('download_used', sa.Boolean(), nullable=True))
    op.drop_column('list', 'expiration_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list', sa.Column('expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('list', 'download_used')
    # ### end Alembic commands ###
