"""empty message

Revision ID: f53886c3a590
Revises: ca3ed81a5c89
Create Date: 2025-02-26 17:09:35.729699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53886c3a590'
down_revision: Union[str, None] = 'ca3ed81a5c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'approved')
    # ### end Alembic commands ###
